In [1]:
# task 1 - lexicon
# Lexicon -> collection of words/Phrases + Information (POS; tense Definitions..)
# Lexicon has lexical entries -> each entry is Word/Phrase -> has a HeadWord(Lemma) + Information

In [2]:
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [3]:
#2 .cmu wordlist
import nltk
entries = nltk.corpus.cmudict.entries()
len(entries)

133737

In [4]:
# wordnet
from nltk.corpus import wordnet as wn
wn.synsets('motorcar')

[Synset('car.n.01')]

In [5]:
wn.synset('car.n.01').lemma_names()

['car', 'auto', 'automobile', 'machine', 'motorcar']

In [6]:
wn.synsets('good')

[Synset('good.n.01'),
 Synset('good.n.02'),
 Synset('good.n.03'),
 Synset('commodity.n.01'),
 Synset('good.a.01'),
 Synset('full.s.06'),
 Synset('good.a.03'),
 Synset('estimable.s.02'),
 Synset('beneficial.s.01'),
 Synset('good.s.06'),
 Synset('good.s.07'),
 Synset('adept.s.01'),
 Synset('good.s.09'),
 Synset('dear.s.02'),
 Synset('dependable.s.04'),
 Synset('good.s.12'),
 Synset('good.s.13'),
 Synset('effective.s.04'),
 Synset('good.s.15'),
 Synset('good.s.16'),
 Synset('good.s.17'),
 Synset('good.s.18'),
 Synset('good.s.19'),
 Synset('good.s.20'),
 Synset('good.s.21'),
 Synset('well.r.01'),
 Synset('thoroughly.r.02')]

In [7]:
wn.synset('good.n.02').lemma_names()

['good', 'goodness']

In [8]:
# task 2- simple text classifier
def gender_features(word):
    return {'last_letter':word[-1]}

In [9]:
gender_features('Obama')

{'last_letter': 'a'}

In [10]:
from nltk.corpus import names
labeled_names = ([(name,'male') for name in names.words('male.txt')]+
[(name,'female') for name in names.words('female.txt')])

In [11]:
import random
random.shuffle(labeled_names)

In [12]:
featuresets = [(gender_features(n),gender) for (n,gender) in labeled_names]

In [13]:
train_set, test_set = featuresets[500:],featuresets[:500]

In [14]:
import nltk
classifier = nltk.NaiveBayesClassifier.train(train_set)

In [15]:
classifier.classify(gender_features('David'))

'male'

In [16]:
classifier.classify(gender_features('Michelle'))

'female'

In [17]:
classifier.classify(gender_features('Obama'))

'female'

In [18]:
print(nltk.classify.accuracy(classifier,test_set))

0.752


In [19]:
classifier.classify(gender_features('Penny'))

'female'

In [20]:
classifier.classify(gender_features('Sheldon'))

'male'

In [21]:
# task 3 -vectorisers & cosine similarity
from sklearn.feature_extraction.text import CountVectorizer
#from from sklearn.feature_extraction.text import TfidfVectorizer

In [22]:
vect = CountVectorizer(binary=True)
corpus = ["Tessaract is good optical character recognition engine  ", "optical character recognition is significant "]
vect.fit(corpus)

CountVectorizer(analyzer='word', binary=True, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [23]:
vocab = vect.vocabulary_

In [24]:
for key in sorted(vocab.keys()):
    print("{}:{}".format(key, vocab[key]))

character:0
engine:1
good:2
is:3
optical:4
recognition:5
significant:6
tessaract:7


In [25]:
print(vect.transform(["This is a good optical illusion"]).toarray())

[[0 0 1 1 1 0 0 0]]


In [26]:
print(vect.transform(corpus).toarray())

[[1 1 1 1 1 1 0 1]
 [1 0 0 1 1 1 1 0]]


In [27]:
from sklearn.metrics.pairwise import cosine_similarity

In [28]:
similarity = cosine_similarity(vect.transform(["Google Cloud Vision is a character recognition engine"]).toarray(), vect.transform(["OCR is an optical character recognition engine"]).toarray())

In [29]:
similarity

array([[0.89442719]])

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [31]:
vectorizer = TfidfVectorizer()
corpus = ["Tessaract is good optical character recognition engine  ", "optical character recognition is significant "]
vectorizer.fit(corpus)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [32]:
vocab2 = vectorizer.vocabulary_

In [33]:
for key in sorted(vocab2.keys()):
    print("{}:{}".format(key, vocab2[key]))

character:0
engine:1
good:2
is:3
optical:4
recognition:5
significant:6
tessaract:7


In [34]:
print(vectorizer.transform(["This is a good optical illusion"]).toarray())

[[0.         0.         0.70490949 0.50154891 0.50154891 0.
  0.         0.        ]]
